Do not build binary for Mac

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -71,62 +71,62 @@ jobs:
             workspace.tar.gz
           if-no-files-found: error
 
-  macos:
-    name: MacOS (PM ${{ matrix.pm-version-major }})
-    runs-on: macos-11.0
-    strategy:
-      matrix:
-        pm-version-major: [ 5 ]
+  # macos:
+  #   name: MacOS (PM ${{ matrix.pm-version-major }})
+  #   runs-on: macos-11.0
+  #   strategy:
+  #     matrix:
+  #       pm-version-major: [ 5 ]
 
-    steps:
-      - uses: actions/checkout@v4
+  #   steps:
+  #     - uses: actions/checkout@v4
       
-      - name: Install tools and dependencies
-        run: brew install libtool autoconf automake pkg-config bison re2c
+  #     - name: Install tools and dependencies
+  #       run: brew install libtool autoconf automake pkg-config bison re2c
         
-      - name: Prepare compile.sh download cache
-        id: download-cache
-        uses: actions/cache@v3
-        with:
-          path: ./download_cache
-          key: compile-sh-cache-ssl-https-${{ hashFiles('./compile.sh') }}
-          restore-keys: compile-sh-cache-ssl-https-
+  #     - name: Prepare compile.sh download cache
+  #       id: download-cache
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: ./download_cache
+  #         key: compile-sh-cache-ssl-https-${{ hashFiles('./compile.sh') }}
+  #         restore-keys: compile-sh-cache-ssl-https-
 
-      - name: Compile PHP
-        run: |
-          export PATH="/usr/local/opt/bison/bin:$PATH"
-          set -ex
-          trap "exit 1" ERR
-          ./compile.sh -t mac-x86-64 -j4 -g -P ${{ matrix.pm-version-major }} -c ./download_cache -D
+  #     - name: Compile PHP
+  #       run: |
+  #         export PATH="/usr/local/opt/bison/bin:$PATH"
+  #         set -ex
+  #         trap "exit 1" ERR
+  #         ./compile.sh -t mac-x86-64 -j4 -g -P ${{ matrix.pm-version-major }} -c ./download_cache -D
           
-      - name: Create tarball
-        run: |
-          tar -czf ./PHP-MacOS-x86_64-PM${{ matrix.pm-version-major }}.tar.gz bin
-          tar -czf ./PHP-MacOS-x86_64-PM${{ matrix.pm-version-major }}-debugging-symbols.tar.gz bin-debug
+  #     - name: Create tarball
+  #       run: |
+  #         tar -czf ./PHP-MacOS-x86_64-PM${{ matrix.pm-version-major }}.tar.gz bin
+  #         tar -czf ./PHP-MacOS-x86_64-PM${{ matrix.pm-version-major }}-debugging-symbols.tar.gz bin-debug
         
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v3
-        if: always()
-        with:
-          name: MacOS-PM${{ matrix.pm-version-major }}
-          path: |
-            ./PHP-MacOS-x86_64-PM${{ matrix.pm-version-major }}*.tar.gz
-            install.log
-            compile.sh
-          if-no-files-found: error
+  #     - name: Upload artifacts
+  #       uses: actions/upload-artifact@v3
+  #       if: always()
+  #       with:
+  #         name: MacOS-PM${{ matrix.pm-version-major }}
+  #         path: |
+  #           ./PHP-MacOS-x86_64-PM${{ matrix.pm-version-major }}*.tar.gz
+  #           install.log
+  #           compile.sh
+  #         if-no-files-found: error
 
-      - name: Prepare workspace for upload
-        if: failure()
-        run: tar -czf workspace.tar.gz install_data
+  #     - name: Prepare workspace for upload
+  #       if: failure()
+  #       run: tar -czf workspace.tar.gz install_data
 
-      - name: Upload workspace
-        uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: MacOS-workspace-PM${{ matrix.pm-version-major }}
-          path: |
-            workspace.tar.gz
-          if-no-files-found: error
+  #     - name: Upload workspace
+  #       uses: actions/upload-artifact@v3
+  #       if: failure()
+  #       with:
+  #         name: MacOS-workspace-PM${{ matrix.pm-version-major }}
+  #         path: |
+  #           workspace.tar.gz
+  #         if-no-files-found: error
 
   windows:
     name: Windows (PM ${{ matrix.pm-version-major }})
@@ -168,7 +168,7 @@ jobs:
 
   publish:
     name: Publish binaries
-    needs: [linux, macos, windows]
+    needs: [linux, windows]
     runs-on: ubuntu-20.04
     if: ${{ startsWith(github.ref_name, 'php/') && github.ref_type == 'branch' && !contains(github.event.head_commit.message, '[no release]') }}
 
